name: Maven CI with Dependency Submission

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Submit Maven Dependencies Snapshot
      uses: advanced-security/maven-dependency-submission-action@v1
      with:
        # Specify your project's pom.xml path if not in the root
        pom_file: 'pom.xml'
        # Pass the PAT as a secret
        token: ${{ secrets.DEPENDENCY_SUBMISSION_TOKEN }}
